site_name: Galaxygine Documentation
theme:
    name: material
    features:
        - navigation.top
    palette:
        # Dark Mode
        - scheme: slate
          toggle:
              icon: material/brightness-4
              name: Switch to light mode
        # Light Mode
        - scheme: default
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode

repo_url: https://github.com/GalaxyGamingBoy/Galaxygine

markdown_extensions:
    - tables
    - def_list
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

nav:
    - Home: index.md
    - Getting Started: getting_started.md
    - Engine:
          - Galaxygine:
                - Galaxygine: engine/galaxygine.md
                - Core: engine/galaxygine/core.md
                - Draw: engine/galaxygine/draw.md
                - InputHandler: engine/galaxygine/input_handler.md
                - Sound: engine/galaxygine/sound.md
          - Renderer:
                - Renderer: engine/renderer/renderer.md
                - RenderObject: engine/renderer/renderObject.md
                - Other RenderObjects: engine/renderer/renderObjectOther.md
          - Utils:
                - Vector2: engine/utils/vector2.md
                - Settings: engine/utils/settings.md
                - Color: engine/utils/color.md
    - Resouces:
          - Resources: res/resources.md
          - keyActions: res/keyAction.md
    - About:
          - Contributions: about/contributions.md
          - License: about/license.md
